name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: npm install

      - name: Run linter
        run: npm run lint 
  deploy: 
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
    needs: [eslint]
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
            heroku_api_key: ${{secrets.HEROKU_API_KEY}}
            heroku_app_name: "ubademy-webadmin-app" #Must be unique in Heroku
            heroku_email: "daniela.leloutre@gmail.com"
            usedocker: false